# Generated by Django 4.2.3 on 2023-07-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPatients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='registrationDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='RegistrationDate'),
        ),
    ]
