# Generated by Django 4.2.4 on 2023-08-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPatients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='city',
        ),
    ]
