# Generated by Django 4.2.4 on 2023-09-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPatients', '0002_remove_patients_address_remove_patients_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, verbose_name='RegistrationDate'),
        ),
    ]
