# Generated by Django 4.2.3 on 2023-07-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMedicalHistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
